<template>
  <div class="canvasWrap">
    <div
      id="editWaveArea"
      class="waveArea"
    >
      <div
        id="selHandleL"
        class="selHandle"
        aria-hidden="true"
      ></div>
      <div
        id="selHandleR"
        class="selHandle"
        aria-hidden="true"
      ></div>
      <div
        id="playheadHandle"
        class="playheadHandle"
        aria-hidden="true"
      ></div>
      <canvas
        id="editScope"
        class="waveCanvas"
        width="1200"
        height="240"
      ></canvas>
    </div>
  </div>
</template>
